# REPLACE EVERYTHING IN CURLY BRACKETS {}, INCLUDING THE BRACKETS THEMSELVES.
# THEN RENAME THIS FILE TO constants.py AND MOVE IT INTO YOUR PROJECT'S ROOT

CONNECT_BASE_URL = '{YOUR BASE URL}/api/xml?action='
CONNECT_LOGIN = '{YOUR LOGIN}'
CONNECT_PWD = '{YOUR PASSWORD}'

# USERS YOU WANT TO BE ABLE TO EXCLUDE FROM REPORTS
CONNECT_ADMIN_USERS = ['{USER1LOGIN}',
                      '{USER2LOGIN}',
                      '{USER3LOGIN}'
                      ]
